install.packages("rpart.plot")
install.packages("rpart")
library("rpart")
library("rpart.plot")
play<-c('yes','no','yes','no','yes','yes','yes','yes','yes','no')
outlook<-c('rainy','rainy','overcast','sunny','rainy','sunny','rainy','sunny','overcast','sunny')
Temp<-c('cool','cool','hot','mild','cool','cool','cool','hot','mild','mild')
humid<-c('normal','normal','high','high','normal','normal','normal','normal','high','high')
wind<-c('FALSE','TRUE','FALSE','FALSE','FALSE','FALSE','FALSE','FALSE','TRUE','TRUE')
play_decision<-cbind(play,outlook,Temp,humid,wind)
play_decision
class(play_decision)
summary(play_decision)
play_decision=as.data.frame(play_decision)
play_decision
str(play_decision)
summary(play_decision)
fit=rpart(play~outlook+Temp+humid+wind,method="class",data=play_decision,control=rpart.control(minsplit=1),parms=list(split='information'))
fit 
str(fit)
rpart.plot
rpart.plot(fit,type=4,extra=1)
rpart.plot(fit,type=4,extra=2,clip.right.labs=FALSE,varlen=0,faclen=0)
